model_params:
  architecture: qwen3-8b
  discovered_at: '2025-06-13T16:57:30Z'
  hidden_dimension: 4096
  model_name: hf.co/unsloth/DeepSeek-R1-0528-Qwen3-8B-GGUF:Q4_K_M
runtime_params:
  batch_size: 1
  device: auto
  dtype: float32
tpv_params:
  activation: gelu
  dropout: 0.1
  num_heads: 8

# Phase 2: Active Control Parameters
control_params:
  completion_threshold: 0.92    # Score above which reasoning is considered complete
  plateau_threshold: 0.005      # If score delta is less than this for N steps, halt
  plateau_patience: 3           # Number of steps to wait for improvement before halting
  max_tokens: 500              # Maximum tokens before forced halt
  min_steps: 2                 # Minimum steps before allowing early termination

# Phase 4: Production Deployment Configuration
deployment_params:
  # Default to opt-in for initial rollout (engineering maturity approach)
  tpv_enabled_by_default: false

  # User control settings
  allow_user_override: true
  show_performance_warning: true

  # Monitoring and telemetry
  enable_telemetry: true
  log_interventions: true
  collect_feedback: true

  # Performance optimization flags
  enable_optimizations: true
  use_model_quantization: false  # Will be enabled after optimization
  use_onnx_runtime: false       # Will be enabled after optimization
